### ISSUE TITLE
[Bug] Array URL parameters get serialized in wrong order

### ISSUE THREAD

**Issue by K1NXZ** [JRomainG/MangaDexLib#2]
When calling `getMangaList()` with specific ids on `MDMangaFilter` , the ids get sometimes (randomly) serialized in wrong order with `JSONSerialization`. The query gets encoded into a dictionary which has no order.   This leads to an error from the MangaDex API.

An example of url which gets parsed right now:
https://api.mangadex.org/manga?ids[3]=79108b0d-64e1-4fad-bd7e-391964f452b1&ids[2]=009dd5f9-8a5d-4f15-8acc-11dbebd2444c&ids[1]=e54ac81c-f64a-4f9e-a96d-5bcde66e7798&ids[0]=8a785b56-b34d-4f86-b8a5-2a626ba64cee&includes[0]=cover_art&includes[1]=artist&includes[2]=author

How it should be (indices in right order):
https://api.mangadex.org/manga?ids[0]=79108b0d-64e1-4fad-bd7e-391964f452b1&ids[1]=009dd5f9-8a5d-4f15-8acc-11dbebd2444c&ids[2]=e54ac81c-f64a-4f9e-a96d-5bcde66e7798&ids[3]=8a785b56-b34d-4f86-b8a5-2a626ba64cee&includes[0]=cover_art&includes[1]=artist&includes[2]=author

The error:
```json
{
    "result": "error",
    "errors": [
        {
            "id": "9c346772-7b14-5982-b4b6-7b5888522762",
            "status": 400,
            "title": "validation_exception",
            "detail": "Error validating /ids: Array value found, but an array is required",
            "context": null
        }
    ]
}
```

The code responsible for that is:
```swift
/// Encode an object to a dictionary
/// - Parameter object: The type of object to return
/// - Returns: The instanciated object
static func encode<T: Encodable>(object: T) throws -> [String: Any]? {
    // Make sure dates are formatted in the way the MangaDex API expects them to be
    let formatter = DateFormatter()
    formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss"
    formatter.timeZone = TimeZone(secondsFromGMT: 0)

    let encoder = JSONEncoder()
    encoder.dateEncodingStrategy = .formatted(formatter)
    let data = try encoder.encode(object)
    return try JSONSerialization.jsonObject(with: data, options: .allowFragments) as? [String: Any]
}
```

found in: `MDParser.swift`

**Comment by JRomainG** [comment]
Should be fixed by the commit above, added a test case for this kind of request
